### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by halprin** [flexion/devops-deployment-metrics#134]
I propose that a GitHub Action is created for this repository to make it easy for others to onboard to gather their metrics.  Instead of manually writing out a [larger workflow file](https://github.com/CDCgov/trusted-intermediary/blob/main/.github/workflows/metrics.yml), let's have a GitHub Action created to make it easier for people to collect the metrics.

I'm thinking something akin to the [actions/setup-python](https://github.com/actions/setup-python).  Meaning, one can put the following into a workflow...

```yaml
- uses: flexion/devops-deployment-metrics@v1 
  with:
    time-slice-days: 7
    start-date: 2022-12-01T00:01:00
    owner: CDCgov
    repo: trusted-intermediary
    # etcetera
```

... and it does the same as what the [large workflow](https://github.com/CDCgov/trusted-intermediary/blob/main/.github/workflows/metrics.yml) above does.
